# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [3]:
import numpy as np

2. Create a null vector of size 10 

In [4]:
a=np.zeros((10))
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [5]:
x=np.arange(10,50)   
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [6]:
x.shape


(40,)

5. Print the type of the previous array in question 3

In [7]:
x.dtype  

dtype('int32')

6. Print the numpy version and the configuration


In [8]:
np.version,np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/AnaConda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/AnaConda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/AnaConda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/AnaConda3\\Library\\include']
la

(<module 'numpy.version' from 'E:\\AnaConda3\\lib\\site-packages\\numpy\\version.py'>,
 None)

7. Print the dimension of the array in question 3


In [9]:
x.ndim 

1

8. Create a boolean array with all the True values

In [10]:
x<50  

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

9. Create a two dimensional array




In [13]:
arr2d=np.array([[1,2],[4,5]])
arr2d

array([[1, 2],
       [4, 5]])

10. Create a three dimensional array



In [15]:
arr3d=np.array([[[1,2,3],[4,5,7],[7,8,9]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 7],
        [7, 8, 9]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [16]:
a=np.array([1,2,3,4,5])
b=np.flip(a)
a,b

(array([1, 2, 3, 4, 5]), array([5, 4, 3, 2, 1]))

12. Create a null vector of size 10 but the fifth value which is 1 

In [17]:
x=np.zeros(10)        
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [22]:
from numpy import eye
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [23]:
arr=np.array([1,2,3,4,5]) 
arr.astype(float)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [193]:
arr1=np.array([[1,2,3],[4,5,6]],dtype=float)
arr2=np.array([[0,4,1],[7,2,12]],dtype=float)
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [194]:
arr=np.maximum(arr1,arr2)
arr

array([[ 1.,  4.,  3.],
       [ 7.,  5., 12.]])

17. Extract all odd numbers from arr with values(0-9)

In [26]:
l=np.array([0,1,2,3,4,5,6,7,8,9])
l[l%2==1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [27]:
l=np.array([0,1,2,3,4,5,6,7,8,9])
y=np.where(l%2==0,l,-1)
y

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [28]:
arr=np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [29]:
arr=np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1]])
arr[1:2,1:3]=0
arr

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [30]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [36]:
arr3d = np.array([[[1, 2, 3], 
                   [4, 5, 6]],
                   [[7, 8, 9],
                   [10,11,12]]])
arr3d[0:1]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [39]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[0:1,0:1]

array([[0]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [40]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[1:,1:2]

array([[6]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [41]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[0:2,2:3]

array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [72]:
x=np.random.randn(10,10)
x_max=np.max(x)
x_min=np.min(x)
x,x_max,x_min


(array([[-0.71616429,  0.29027111,  2.7068501 ,  0.14780224, -1.24826286,
          0.68991477, -0.58415041, -0.11303819,  0.64792817, -0.4737654 ],
        [ 0.32645075, -0.21146752,  1.32718852,  1.23281763,  0.94077532,
          0.05615748, -0.24360745, -0.31105402,  0.18202349, -1.719763  ],
        [-0.47707013,  1.80478443,  1.58063948, -1.04589832, -0.83638374,
         -0.98653884, -1.00307247,  0.38188297, -0.25327917,  0.79674043],
        [-0.09106294, -0.10999261, -0.98410917, -0.28352923,  1.53907225,
         -1.02080067, -1.55264538, -0.05141362,  1.45358551,  0.2173145 ],
        [ 1.34135374,  0.97989178, -0.69528871, -0.53876748, -0.03998742,
          1.39012092,  0.51186008,  1.36138828, -1.35331405,  0.97450358],
        [ 0.20533962, -0.07220428,  0.33133327, -0.24528383,  0.65824483,
         -1.13846294, -0.46524036, -0.77472433,  0.45834793, -0.56405891],
        [ 0.66971863,  0.24654664, -1.80435018, -0.57529925,  0.07116491,
         -0.24460354, -1.7493622

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [182]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



TypeError: _repeat_dispatcher() missing 1 required positional argument: 'repeats'

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [79]:
names=np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names!="Will"]

array([[ 0.59892789,  1.42137876, -1.98108983, -1.252241  ],
       [ 0.99088632,  0.68452662, -1.70172161,  0.36294582],
       [ 0.52499684, -1.24509732, -0.2757552 , -1.38698572],
       [ 2.56907572,  0.17897706,  0.5235592 , -1.03287682],
       [-0.09142366, -1.05761754,  0.69126437,  0.42934851]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [90]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names=="Bob"]

array([[ 0.11135489,  1.49809399, -1.60893795, -2.40862184],
       [ 1.04939075, -0.2078479 , -1.42633654,  1.77661529]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [92]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [94]:
arr3d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [158]:
arr3d.T

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [112]:
arr=np.arange(10)
arr_sqrt=np.sqrt(arr)
arr_sqrt[0]=0
arr,  arr_sqrt

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]))

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [118]:
arr1=np.random.rand(12)
arr2=np.random.rand(12)
arr=np.maximum(arr1,arr2)
arr1,arr2,arr

(array([0.33815642, 0.75831671, 0.07237369, 0.36470155, 0.77583139,
        0.5403101 , 0.52370331, 0.13621368, 0.93804214, 0.06361044,
        0.32655037, 0.44609145]),
 array([0.52631155, 0.63912578, 0.93450714, 0.37823551, 0.91144607,
        0.11835617, 0.42017707, 0.31416485, 0.40455299, 0.87945245,
        0.64738308, 0.56559487]),
 array([0.52631155, 0.75831671, 0.93450714, 0.37823551, 0.91144607,
        0.5403101 , 0.52370331, 0.31416485, 0.93804214, 0.87945245,
        0.64738308, 0.56559487]))

In [121]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
y=np.unique(names)
z=np.sort(y)
y,z

(array(['Bob', 'Joe', 'Will'], dtype='<U4'),
 array(['Bob', 'Joe', 'Will'], dtype='<U4'))

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [139]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
y=np.setdiff1d(a,b)
y

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [152]:
Array = np.array([[34,43,73],[82,22,12],[53,94,66]])
y=np.delete(Array,1,1)
z=np.insert(y,1,[10,10,10],1)
y,z

(array([[34, 73],
        [82, 12],
        [53, 66]]),
 array([[34, 10, 73],
        [82, 10, 12],
        [53, 10, 66]]))

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [162]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y_new=y.reshape(2,3)
x*y_new

array([[ 6., 46., -3.],
       [28., 40., 54.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [179]:
x=np.random.rand(20)
x_new=np.matrix(x)
C_Sum=np.cumsum(x_new)
x_new,C_Sum

(matrix([[0.68797391, 0.35885305, 0.46334509, 0.46514801, 0.67696772,
          0.79072744, 0.67879704, 0.45539119, 0.4888138 , 0.20684655,
          0.02375308, 0.88742598, 0.25823862, 0.70368315, 0.2414206 ,
          0.09553414, 0.91853099, 0.89349465, 0.69036556, 0.30587204]]),
 matrix([[ 0.68797391,  1.04682695,  1.51017204,  1.97532005,  2.65228776,
           3.4430152 ,  4.12181224,  4.57720343,  5.06601723,  5.27286378,
           5.29661686,  6.18404284,  6.44228146,  7.14596461,  7.38738521,
           7.48291935,  8.40145034,  9.29494499,  9.98531055, 10.29118259]]))