# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr=np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
arr1=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr2=np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
arr1=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr2=np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
arr1=np.array([[0, 1],[2, 3],[4,5],[6, 7],[8,9]])
arr1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
arr=np.arange(15).reshape(3,1,1,5)
arr1=arr.flatten()
print(arr)
print(arr1)

[[[[ 0  1  2  3  4]]]


 [[[ 5  6  7  8  9]]]


 [[[10 11 12 13 14]]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
arr=np.array([ 0 , 1,  2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 ,10 ,11, 12 ,13 ,14])
arr.reshape((5,1,1,3))

array([[[[ 0,  1,  2]]],


       [[[ 3,  4,  5]]],


       [[[ 6,  7,  8]]],


       [[[ 9, 10, 11]]],


       [[[12, 13, 14]]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
arr=np.random.rand(25).reshape(5,5)
arr1=np.square(arr)
print(arr)
print(arr1)

[[0.15002159 0.60223836 0.26908737 0.95383993 0.7779361 ]
 [0.14443265 0.22167343 0.83856959 0.77609853 0.54637815]
 [0.09969674 0.22702993 0.65702159 0.07304984 0.82399017]
 [0.71527663 0.21948703 0.44793572 0.33192708 0.29513059]
 [0.21060773 0.72336944 0.8877415  0.57537163 0.60084155]]
[[0.02250648 0.36269104 0.07240801 0.9098106  0.60518457]
 [0.02086079 0.04913911 0.70319895 0.60232893 0.29852908]
 [0.00993944 0.05154259 0.43167737 0.00533628 0.6789598 ]
 [0.51162066 0.04817456 0.20064641 0.11017559 0.08710206]
 [0.04435562 0.52326335 0.78808497 0.33105252 0.36101057]]


## Question:8

### Create 5x6 an array and find the mean?

In [29]:
arr=np.random.rand(30).reshape(5,6)
a_mean=arr.mean()
print(arr)
print("Mean = ",a_mean)

[[0.15594191 0.33737027 0.98549046 0.30780118 0.87089159 0.1475346 ]
 [0.68756951 0.0589581  0.77595476 0.89316965 0.29529158 0.37321485]
 [0.32817029 0.64211455 0.92469707 0.60963727 0.587264   0.90395283]
 [0.36720312 0.96214219 0.88524932 0.44401847 0.81232202 0.32636729]
 [0.50783606 0.68714613 0.5152071  0.0099583  0.33131569 0.298104  ]]
Mean =  0.5343964716946901


## Question:9

### Find the standard deviation of the previous array in Q8?

In [30]:
a_std=arr.std()
print("standard deviation = ",a_std)

standard deviation =  0.2846172592879199


## Question:10

### Find the median of the previous array in Q8?

In [31]:
median=np.median(arr)
print("median =", median)

median = 0.5115215821822892


## Question:11

### Find the transpose of the previous array in Q8?

In [32]:
arr.T
print("Transpose =",arr.T)

Transpose = [[0.15594191 0.68756951 0.32817029 0.36720312 0.50783606]
 [0.33737027 0.0589581  0.64211455 0.96214219 0.68714613]
 [0.98549046 0.77595476 0.92469707 0.88524932 0.5152071 ]
 [0.30780118 0.89316965 0.60963727 0.44401847 0.0099583 ]
 [0.87089159 0.29529158 0.587264   0.81232202 0.33131569]
 [0.1475346  0.37321485 0.90395283 0.32636729 0.298104  ]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [44]:
arr=np.arange(4*4).reshape((4,4))
arr_dia=np.trace(arr)
print(arr)
print("sum of diagonal elements = ",arr_dia)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
sum of diagonal elements =  30


## Question:13

### Find the determinant of the previous array in Q12?

In [46]:
arr=np.arange(16).reshape((4,4))
Det=np.linalg.det(arr)
print(arr)
print(Det)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-2.9582283945787796e-30


## Question:14

### Find the 5th and 95th percentile of an array?

In [52]:
a=np.percentile(arr,5)
b=np.percentile(arr,95)
print("5th percentile of an array =",a)
print("95th percentile of an array =",b)

5th percentile of an array = 0.75
95th percentile of an array = 14.25


## Question:15

### How to find if a given array has any null values?

In [57]:
a=np.array([1,2,0,4,5,8,9,15]) 
np.where(a==0)


(array([2], dtype=int32),)