# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

In [2]:
a=np.zeros((10))
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
x=np.arange(10,50)   
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
x.shape


(40,)

5. Print the type of the previous array in question 3

In [5]:
x.dtype  

dtype('int32')

6. Print the numpy version and the configuration


In [6]:
np.version,np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/AnaConda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/AnaConda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/AnaConda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/AnaConda3\\Library\\include']
la

(<module 'numpy.version' from 'E:\\AnaConda3\\lib\\site-packages\\numpy\\version.py'>,
 None)

7. Print the dimension of the array in question 3


In [7]:
x.ndim 

1

8. Create a boolean array with all the True values

In [8]:
x<50  

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

9. Create a two dimensional array




In [9]:
arr2d=np.array([[1,2],[4,5]])
arr2d

array([[1, 2],
       [4, 5]])

10. Create a three dimensional array



In [10]:
arr3d=np.array([[[1,2,3],[4,5,7],[7,8,9]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 7],
        [7, 8, 9]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
a=np.array([1,2,3,4,5])
b=np.flip(a)
a,b

(array([1, 2, 3, 4, 5]), array([5, 4, 3, 2, 1]))

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
x=np.zeros(10)        
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
from numpy import eye
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr=np.array([1,2,3,4,5]) 
arr.astype(float)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [59]:
arr1=np.array([[1,2,3],[4,5,6]],dtype=float)
arr2=np.array([[0,4,1],[7,2,12]],dtype=float)
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [64]:
arr[arr1!=arr2]

array([ 1.,  4.,  3.,  7.,  5., 12.])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
l=np.array([0,1,2,3,4,5,6,7,8,9])
l[l%2==1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [18]:
l=np.array([0,1,2,3,4,5,6,7,8,9])
y=np.where(l%2==0,l,-1)
y

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr=np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
arr=np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1]])
arr[1:2,1:3]=0
arr

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], 
                   [4, 5, 6]],
                   [[7, 8, 9],
                   [10,11,12]]])
arr3d[0:1]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[0:1,0:1]

array([[0]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[1:,1:2]

array([[6]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[0:2,2:3]

array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
x=np.random.randn(10,10)
x_max=np.max(x)
x_min=np.min(x)
x,x_max,x_min


(array([[-0.23615852,  0.51680928, -0.38774288, -1.96241101, -0.45328092,
          0.99217083, -0.24751231,  0.09951863, -0.42113294,  0.84445628],
        [-1.17186722,  0.27858552, -1.74273096, -1.21445406,  1.80511389,
          0.24774291,  0.25137893,  0.10579353, -0.96723756,  1.47922962],
        [ 0.2484846 ,  0.87683669, -1.68548509, -0.64578969, -2.08251641,
         -0.29428472, -0.15959945,  0.59682448,  1.01335046, -0.47204354],
        [ 0.40674124, -0.55121383,  0.05584683,  1.48961128,  2.2173246 ,
          0.2952622 , -0.58159209,  0.57774737,  0.996422  ,  0.54635076],
        [ 0.49872318,  0.76901201,  1.57121434, -0.2123288 ,  1.01450909,
          0.07461997, -0.26815292, -0.16524062,  0.2293881 ,  0.91035947],
        [-0.03051143, -0.89787334,  1.059288  ,  1.44735831, -0.02613116,
          0.09497913, -1.15392589, -0.85396037, -0.25639495,  1.55796168],
        [-0.42307052,  1.0553304 , -0.28847524,  1.08228296, -0.51384459,
          0.43864837,  1.2580706

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [28]:
names=np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names!="Will"]

array([[ 0.42517992, -0.1263735 , -0.30511258,  0.50989979],
       [-1.21556143,  0.91019917, -0.23586907,  0.58237047],
       [-0.18844119,  0.23839407, -0.44163498,  0.27232107],
       [ 0.52275742,  0.07672322,  1.70355484,  1.30160844],
       [-1.1165449 ,  0.97732888,  0.11396813,  1.51488528]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names=="Bob"]

array([[ 0.75485443, -1.43134371, -0.69949321,  0.63117437],
       [ 0.49082792, -0.64685064,  1.72225416,  1.36121032]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [30]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [31]:
arr3d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [32]:
arr3d.T

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [33]:
arr=np.arange(10)
arr_sqrt=np.sqrt(arr)
arr_sqrt[0]=0
arr,  arr_sqrt

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]))

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [34]:
arr1=np.random.rand(12)
arr2=np.random.rand(12)
arr=np.maximum(arr1,arr2)
arr1,arr2,arr

(array([0.85617076, 0.5563207 , 0.90480813, 0.95295312, 0.09816097,
        0.57377651, 0.77212243, 0.28553424, 0.39684459, 0.35137696,
        0.4017192 , 0.34239333]),
 array([0.49623818, 0.55460621, 0.5635929 , 0.91792422, 0.60130461,
        0.82827748, 0.86387486, 0.09948347, 0.22166941, 0.21556195,
        0.61350323, 0.11653581]),
 array([0.85617076, 0.5563207 , 0.90480813, 0.95295312, 0.60130461,
        0.82827748, 0.86387486, 0.28553424, 0.39684459, 0.35137696,
        0.61350323, 0.34239333]))

In [35]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
y=np.unique(names)
z=np.sort(y)
y,z

(array(['Bob', 'Joe', 'Will'], dtype='<U4'),
 array(['Bob', 'Joe', 'Will'], dtype='<U4'))

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [36]:
import numpy as np
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
y=np.setdiff1d(a,b)
y

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [37]:
Array = np.array([[34,43,73],[82,22,12],[53,94,66]])
y=np.delete(Array,1,1)
z=np.insert(y,1,[10,10,10],1)
y,z

(array([[34, 73],
        [82, 12],
        [53, 66]]),
 array([[34, 10, 73],
        [82, 10, 12],
        [53, 10, 66]]))

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [38]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y_new=y.reshape(2,3)
x*y_new

array([[ 6., 46., -3.],
       [28., 40., 54.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [39]:
x=np.random.rand(20)
x_new=np.matrix(x)
C_Sum=np.cumsum(x_new)
x_new,C_Sum

(matrix([[0.09464063, 0.46456208, 0.53274787, 0.46023453, 0.14165216,
          0.74174545, 0.8202534 , 0.37730276, 0.45675759, 0.03528321,
          0.70496356, 0.78159303, 0.03662583, 0.62114639, 0.45492606,
          0.78266615, 0.6180659 , 0.32516277, 0.86134478, 0.37668892]]),
 matrix([[0.09464063, 0.55920271, 1.09195058, 1.55218511, 1.69383727,
          2.43558272, 3.25583612, 3.63313888, 4.08989648, 4.12517969,
          4.83014325, 5.61173628, 5.64836211, 6.2695085 , 6.72443457,
          7.50710072, 8.12516662, 8.45032938, 9.31167416, 9.68836308]]))

In [40]:
arr1=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr2=np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
arr1=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr2=np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [42]:
arr=np.arange(15).reshape(3,1,1,5)
arr1=arr.flatten()
print(arr)
print(arr1)

[[[[ 0  1  2  3  4]]]


 [[[ 5  6  7  8  9]]]


 [[[10 11 12 13 14]]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [43]:
arr=np.array([ 0 , 1,  2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 ,10 ,11, 12 ,13 ,14])
arr.reshape((5,1,1,3))

array([[[[ 0,  1,  2]]],


       [[[ 3,  4,  5]]],


       [[[ 6,  7,  8]]],


       [[[ 9, 10, 11]]],


       [[[12, 13, 14]]]])

In [44]:
arr=np.random.rand(25).reshape(5,5)
arr1=np.square(arr)
print(arr)
print(arr1)

[[0.7508244  0.69785097 0.28562528 0.29346002 0.90191932]
 [0.24805999 0.34640791 0.96206326 0.01607604 0.99095503]
 [0.2105757  0.62726348 0.86831849 0.36958982 0.95020578]
 [0.06295443 0.7909304  0.60600109 0.24782013 0.4507657 ]
 [0.79631128 0.7253982  0.88524237 0.78519663 0.76920727]]
[[5.63737276e-01 4.86995973e-01 8.15818016e-02 8.61187854e-02
  8.13458454e-01]
 [6.15337587e-02 1.19998438e-01 9.25565724e-01 2.58438911e-04
  9.81991879e-01]
 [4.43421273e-02 3.93459478e-01 7.53976995e-01 1.36596636e-01
  9.02891016e-01]
 [3.96326014e-03 6.25570893e-01 3.67237322e-01 6.14148165e-02
  2.03189714e-01]
 [6.34111662e-01 5.26202549e-01 7.83654060e-01 6.16533743e-01
  5.91679818e-01]]


In [45]:
arr=np.random.rand(30).reshape(5,6)
a_mean=arr.mean()
print(arr)
print("Mean = ",a_mean)

[[0.33504403 0.86539698 0.75652576 0.97867234 0.97205686 0.32970492]
 [0.00759238 0.40867096 0.75514696 0.1676699  0.94557827 0.74403274]
 [0.09803624 0.41111733 0.44577462 0.68941884 0.84213111 0.79136079]
 [0.43162462 0.59101009 0.55914821 0.29119497 0.0504055  0.78383704]
 [0.55607603 0.17862519 0.96253651 0.44880848 0.08691913 0.81438565]]
Mean =  0.5432834148114808


In [46]:
a_std=arr.std()
print("standard deviation = ",a_std)

standard deviation =  0.2989531492387736


In [ ]:
median=np.median(arr)
print("median =", median)

In [47]:
arr.T
print("Transpose =",arr.T)

Transpose = [[0.33504403 0.00759238 0.09803624 0.43162462 0.55607603]
 [0.86539698 0.40867096 0.41111733 0.59101009 0.17862519]
 [0.75652576 0.75514696 0.44577462 0.55914821 0.96253651]
 [0.97867234 0.1676699  0.68941884 0.29119497 0.44880848]
 [0.97205686 0.94557827 0.84213111 0.0504055  0.08691913]
 [0.32970492 0.74403274 0.79136079 0.78383704 0.81438565]]


In [48]:
arr=np.arange(4*4).reshape((4,4))
arr_dia=np.trace(arr)
print(arr)
print("sum of diagonal elements = ",arr_dia)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
sum of diagonal elements =  30


In [50]:
arr=np.arange(16).reshape((4,4))
Det=np.linalg.det(arr)
print(arr)
print("Determinant =", Det)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Determinant = -2.9582283945787796e-30


In [51]:
a=np.percentile(arr,5)
b=np.percentile(arr,95)
print("5th percentile of an array =",a)
print("95th percentile of an array =",b)

5th percentile of an array = 0.75
95th percentile of an array = 14.25


In [57]:
a=np.array([1,2,0,4,5,8,9,15]) 
a=np.where(a==0)
a

(array([2], dtype=int32),)